---
- name: Create group
  ansible.builtin.group:
    name: docker_files
    state: present

- name: Create docker file user
  ansible.builtin.user:
    create_home: no
    group: docker_files
    name: docker_files
    shell: /sbin/nologin
    state: present

- name: Create app network
  community.docker.docker_network:
    name: app-network
    driver_options:
          com.docker.network.bridge.name: br-app-network