---
- name: Install docker plugin grafana/loki-docker-driver
  community.docker.docker_plugin: 
    plugin_name: grafana/loki-docker-driver:latest
    alias: loki
    state: present

- name: Enable docker plugin grafana/loki-docker-driver
  community.docker.docker_plugin: 
    plugin_name: grafana/loki-docker-driver
    state: enable
  notify: restart docker

- name: Create group
  ansible.builtin.group:
    name: "{{ docker_custom_group }}"
    state: present

- name: Create docker file user
  ansible.builtin.user:
    create_home: no
    group: "{{ docker_custom_group }}"
    name: "{{ docker_custom_user }}"
    shell: /sbin/nologin
    state: present

- name: Create app network
  community.docker.docker_network:
    name: "{{ docker_custom_network }}"
    driver_options:
          com.docker.network.bridge.name: "br-{{ docker_custom_network }}"

- name: adding user Debian-snmp to group docker
  user:
    name: Debian-snmp
    groups: docker
    append: yes
