---
- name: Create group
  ansible.builtin.group:
    name: "{{ docker_custom_group }}"
    state: present

- name: Create docker file user
  ansible.builtin.user:
    create_home: no
    group: "{{ docker_custom_group }}"
    name: "{{ docker_custom_user }}"
    shell: /sbin/nologin
    state: present

- name: adding user Debian-snmp to group docker
  user:
    name: Debian-snmp
    groups: docker
    append: yes
